name: Build Validation

on:
  push:
    branches: [ "master" ]  # Changed to "master" branch
  pull_request:
    branches: [ "master" ]  # Changed to "master" branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild /p:Configuration=Release
