name: Build Validation

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to main branch
  pull_request:
    branches: [ "main" ]  # Trigger on PRs to main branch

jobs:
  build:
    runs-on: windows-latest  # ASP.NET apps work best on Windows runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |  # Match your project's .NET version
            4.8
            6.0.x

      - name: Restore dependencies
        run: nuget restore  # Restore NuGet packages

      - name: Build solution
        run: msbuild /p:Configuration=Release  # Build the solution in Release mode
