name: Build Validation

on:
  push:
    branches: [ "master" ]  
  pull_request:
    branches: [ "master" ]  

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: nuget restore

      - name: Locate MSBuild Path
        shell: cmd
        run: |
          @echo off
          for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath') do set MSBUILD_PATH=%%i
          echo Found MSBuild at: %MSBUILD_PATH%
          echo MSBUILD_PATH=%MSBUILD_PATH%>>%GITHUB_ENV%

      - name: Build solution
        shell: cmd  
        run: |
          "%MSBUILD_PATH%\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release
