name: Build Validation

on:
  push:
    branches: [ "master" ]  # Trigger on pushes to master branch
  pull_request:
    branches: [ "master" ]  # Trigger on PRs to master branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        shell: cmd  # Run this step in CMD instead of PowerShell
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release
